export const URL = Object.freeze({
  ACTIVATE: 'activate',
  CREATE_TOKEN: 'createtToken',
  CREATE_TRANSACTION: 'createTransaction',
  AUTH: 'auth',
  EDIT_PROFILE: 'editProfile',
  GET_TRANSACTION: 'getTransaction',
  GET_USER: 'getUser',
  REGISTER: 'register',
  SEND_EMAIL: 'sendemail',
  SEND_NOTIFICATION: 'sendNotification',
  SEND_PASSWORD_TOKEN: 'sendPasswordToken',
  SET_PROFILE_PICTURE: 'setProfilePicture',
  STRIPE_SESSION: 'stripe-session',
  UPDATE_COUNTRY: 'updateCountry',
  UPDATE_PASSWORD: 'updatePassword',
  UPDATE_STATUS: 'updateStatus',
  UPLOAD_IMAGE: 'upload-image',
  USER_EXISTS: 'userExists',
});
