export const routes = {
  AUTHENTICATE: '/authenticate',
  CARDDETAILS: '/carddetails',
  CHECKOUT: '/checkout',
  DASHBOARD: '/dashboard',
  FASTBUY: '/fastbuy',
  FORGOTPASSWORD: '/forgotpassword',
  LOGIN: '/login',
  NFTCONNECT: '/nftconnect',
  ORDERPROCESSING: '/orderprocessing',
  POOLS: '/pools',
  PROFILE: {
    DEFAULT: '/',
    CAMERA: '/camera',
    COUNTRYANDLANGUAGE: '/countryandlanguage',
    HISTORY: '/history',
    PERSONALINFO: '/personalinfo',
  },
  REDIRECT: '/redirect',
  SIGNUP: '/signup',
  STAKING: '/staking',
  SUCCESS: '/success',
  SWAP: '/swap',
  SWAPPINGOFFER: '/swappingoffer',
  THANKYOU: '/thankyou',
  VERIFY: '/verify',
};
